### PR TITLE
Handle language code, cache and custom errors

### PR DESCRIPTION
**Pull request by Fantomas42**
Hi,

if this pull request give you satisfaction, can you publish a new release on Pypi after the merge ?

Regards

### CODE REVIEW

**Comment by Alir3z4** [comment]
@Fantomas42 This is awesome, I'll merge and issue a release soon.

Thanks.

**Comment by Alir3z4** [comment]
Fixes #1

**Comment by Fantomas42** [comment]
Perfect, thanks for the release.

**Comment by Alir3z4** [comment]
@Fantomas42 Welcome, thanks for the awesome pull-request and your amazing projects <3

**Pull request merged**
