### PR TITLE
LANGUAGE_MAPPING

### PR DESCRIPTION
**Pull request by kissarat**
LANGUAGE_MAPPING is loads from stop-words/languages.json
use os.path.join everywhere

### CODE REVIEW

**Comment by Alir3z4** [comment]
The error seems to be due to stop-words repo is not updated and in sync with python-stop-words.

I update and let you know about it.

**Comment by dmiro** [comment]
@kissarat , I think that you must create pull request from your stop-words repository to @Alir3z4 's stop-word repository

**Comment by Alir3z4** [comment]
@dmiro he did actually. I'm working on it right now

**Comment by Alir3z4** [comment]
continue this on #7

**Pull request closed without merging**
