### PR TITLE
Using the cache is optional

### PR DESCRIPTION
**Pull request by kissarat**

### CODE REVIEW

**Comment by Alir3z4** [comment]
@kissarat it seems that your fork is not updated with mine, please update your fork with the latest of mine.

Also update the version number in **ini**.py therefore I can merge/release right away.

Thaks for the awesome work

**Comment by Alir3z4** [comment]
@kissarat great work on filters.

tests are failing, could you look at the travis please and fix? https://travis-ci.org/Alir3z4/python-stop-words/builds/51761207

**Comment by kissarat** [comment]
It's strange. I ran tests on my laptop before commit (python 2.7 and python 3.4) - they passed OK. So I don't know what to do.

**Comment by Alir3z4** [comment]
the test are passing but `flake` doesn't pass.

Did you run ?

```
./bin/flake8 stop_words
```

**Comment by kissarat** [comment]
flake8 runs without errors

**Comment by Alir3z4** [comment]
okay lemme check on my machine.

**Comment by Alir3z4** [comment]
Thanks for the great work
Latest release: https://github.com/Alir3z4/python-stop-words/releases/tag/2015.2.23

**Comment by dmiro** [comment]
Hi.
I try to install latest version with command `pip install stop_words` and throws an error.
This happens in Windows 7. At the moment I haven't my Linux laptop to test in a Linux enviroment

```
Downloading/unpacking stop-words
  Downloading stop-words-2015.2.23.tar.gz
  Running setup.py (path:c:\users\david~1.mir\appdata\local\temp\pip_build_david
.miro\stop-words\setup.py) egg_info for package stop-words
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "c:\users\david~1.mir\appdata\local\temp\pip_build_david.miro\stop-wo
rds\setup.py", line 5, in <module>
        version=__import__("stop_words").get_version(),
      File "stop_words\__init__.py", line 9, in <module>
        with open(os.path.join(STOP_WORDS_DIR, 'languages.json'), 'rb') as map_f
ile:
    IOError: [Errno 2] No such file or directory: 'c:\\users\\david~1.mir\\appda
ta\\local\\temp\\pip_build_david.miro\\stop-words\\stop_words\\stop-words\\langu
ages.json'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "c:\users\david~1.mir\appdata\local\temp\pip_build_david.miro\stop-words\
setup.py", line 5, in <module>

    version=__import__("stop_words").get_version(),

  File "stop_words\__init__.py", line 9, in <module>

    with open(os.path.join(STOP_WORDS_DIR, 'languages.json'), 'rb') as map_file:


IOError: [Errno 2] No such file or directory: 'c:\\users\\david~1.mir\\appdata\\
local\\temp\\pip_build_david.miro\\stop-words\\stop_words\\stop-words\\languages
.json'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in c:\users\david~1.mi
r\appdata\local\temp\pip_build_david.miro\stop-words
Storing debug log for failure in C:\Users\david.miro\pip\pip.log
```

**Comment by kissarat** [comment]
Yes, languages.json is missing in https://pypi.python.org/packages/source/s/stop-words/stop-words-2015.2.21.tar.gz . But is does not concern to this pull request.

**Comment by Alir3z4** [comment]
@kissarat I release the one with languages.json and from pypi:

```
(defEnv)[alireza@arch pycharm]$ pip install stop-words
Requirement already satisfied (use --upgrade to upgrade): stop-words in ./defEnv/lib/python2.7/site-packages/stop_words-2014.5.26-py2.7.egg
Cleaning up...
(defEnv)[alireza@arch pycharm]$ pip install -U stop-words
Real name of requirement stop-words is stop-words
Downloading/unpacking stop-words from https://pypi.python.org/packages/source/s/stop-words/stop-words-2015.2.23.tar.gz#md5=0ec19164b6259e3514d4f78963c4c6e2
  Downloading stop-words-2015.2.23.tar.gz
  Running setup.py egg_info for package stop-words
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/alireza/dev/pycharm/defEnv/build/stop-words/setup.py", line 5, in <module>
        version=__import__("stop_words").get_version(),
      File "stop_words/__init__.py", line 9, in <module>
        with open(os.path.join(STOP_WORDS_DIR, 'languages.json'), 'rb') as map_file:
    IOError: [Errno 2] No such file or directory: '/home/alireza/dev/pycharm/defEnv/build/stop-words/stop_words/stop-words/languages.json'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/alireza/dev/pycharm/defEnv/build/stop-words/setup.py", line 5, in <module>

    version=__import__("stop_words").get_version(),

  File "stop_words/__init__.py", line 9, in <module>

    with open(os.path.join(STOP_WORDS_DIR, 'languages.json'), 'rb') as map_file:

IOError: [Errno 2] No such file or directory: '/home/alireza/dev/pycharm/defEnv/build/stop-words/stop_words/stop-words/languages.json'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/alireza/dev/pycharm/defEnv/build/stop-words
Storing complete log in /home/alireza/.pip/pip.log

```

**Comment by Alir3z4** [comment]
Fixed: https://github.com/Alir3z4/python-stop-words/releases/tag/2015.2.23.1

**Comment by dmiro** [comment]
It's ok. I completed successfully installation in Windows 7.

**Comment by Alir3z4** [comment]
Awesome, thanks for testing the installation ;)

**Pull request merged**
